### ユーザー情報の取得の処理
GET http://localhost:10001/api/v1/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODgzOTc4MzksInVzZXJfaWQiOjJ9.K2A0acq5wLpK-aJaLdqtyp1Tr68rE92krZ2TzptUKPI
